---

  
  - name: installation des paquets necessaire
    package:
      name: "{{ paquets }}"
      state: latest
    vars:
      paquets:
      - postgresql
      - python3-psycopg2

  - name: Demarrer le service postgres
    service: 
      name: postgresql
      state: started

  - name: gestion de la connexion peer
    template:
      src: ../files/pg_hba.conf
      dest: /etc/postgresql/13/main/pg_hba.conf
    register: hba_status

  - name: Change listen postgres network
    lineinfile:
      path: /etc/postgresql/13/main/postgresql.conf
      line: listen_addresses = '*'
    register: psqlconf

  - name: Redemarrer le service postgres
    service: 
      name: postgresql
      state: restarted
    when: hba_status.changed or psqlconf.changed

  - name: Création d'un utilisateur
    postgresql_user:
      state: present
      name: "{{ peertube_username }}"
      password: "{{ peertube_password }}"
      login_host: 127.0.0.1

  - name: Creation de la base de donnée
    postgresql_db:
      state: present
      name: "{{ peertube_database_name }}"
      login_host: 127.0.0.1
      owner: "{{ peertube_username }}"
  
  - name: "Grant db user access to app db"
    postgresql_privs:
      type: database
      database: "{{ peertube_database_name }}"
      roles: "{{ peertube_username }}"
      grant_option: no
      privs: all
      login_host: 127.0.0.1

  - name: Configurationdes extensions de la BD
    postgresql_ext:
      db: "{{ peertube_database_name }}"
      name: "{{ item }}"
      login_host: 127.0.0.1
    with_items: "{{ postgres_ext }}"
    

  - name: configurer postgresql
    template:
      src: ../files/network_db
      dest: /etc/postgresql/13/main/conf.d
    notify: Redemarrer postgresql
